version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile

    container_name: smart_backend

    ports:
      - "5000:5000"

    env_file:
      - ../backend/.env

    volumes:
      - ../backend:/app
      - /app/node_modules

    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile

    container_name: smart_frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ../frontend:/app
      - /app/node_modules

    restart: always